//go:build ignore

// gen_view_types generates TypeScript type definitions for all registered views.
// Usage: go run scripts/gen_view_types.go > sdk/views.d.ts
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/bizengine/engine/internal/views"
	"github.com/bizengine/engine/internal/views/defs"
)

func main() {
	r := views.NewRegistry()
	defs.RegisterAll(r)

	all := r.All()
	sort.Slice(all, func(i, j int) bool { return all[i].Key < all[j].Key })

	fmt.Fprintln(os.Stdout, "// Auto-generated by gen_view_types.go — do not edit")
	fmt.Fprintf(os.Stdout, "// Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339))

	// Generate params interface for each view.
	for _, def := range all {
		iface := toPascal(def.Key)

		// Params interface
		fmt.Fprintf(os.Stdout, "export interface %sParams {\n", iface)
		if len(def.ParamSchema) > 0 {
			keys := sortedKeys(def.ParamSchema)
			for _, k := range keys {
				tsType := goTypeToTS(def.ParamSchema[k])
				fmt.Fprintf(os.Stdout, "  %s?: %s;\n", k, tsType)
			}
		}
		fmt.Fprintln(os.Stdout, "}")
		fmt.Fprintln(os.Stdout)

		// Result: generic — tables map with refs
		fmt.Fprintf(os.Stdout, "export interface %sResult {\n", iface)
		fmt.Fprintln(os.Stdout, "  refs: DataRef[];")
		fmt.Fprintln(os.Stdout, "  tables: Record<string, Record<string, Record<string, unknown>>>;")
		fmt.Fprintln(os.Stdout, "  version: number;")
		fmt.Fprintln(os.Stdout, "}")
		fmt.Fprintln(os.Stdout)
	}

	// DataRef type
	fmt.Fprintln(os.Stdout, "export interface DataRef {")
	fmt.Fprintln(os.Stdout, "  table: string;")
	fmt.Fprintln(os.Stdout, "  id: string;")
	fmt.Fprintln(os.Stdout, "  fields: string[];")
	fmt.Fprintln(os.Stdout, "}")
	fmt.Fprintln(os.Stdout)

	// PatchOp type
	fmt.Fprintln(os.Stdout, "export interface PatchOp {")
	fmt.Fprintln(os.Stdout, "  op: 'add' | 'remove' | 'replace';")
	fmt.Fprintln(os.Stdout, "  path: string;")
	fmt.Fprintln(os.Stdout, "  value?: unknown;")
	fmt.Fprintln(os.Stdout, "}")
	fmt.Fprintln(os.Stdout)

	// Message types
	fmt.Fprintln(os.Stdout, "export interface ViewSnapshotMsg {")
	fmt.Fprintln(os.Stdout, "  type: 'view_snapshot';")
	fmt.Fprintln(os.Stdout, "  view: string;")
	fmt.Fprintln(os.Stdout, "  params_hash: string;")
	fmt.Fprintln(os.Stdout, "  version: number;")
	fmt.Fprintln(os.Stdout, "  refs: DataRef[];")
	fmt.Fprintln(os.Stdout, "  tables: Record<string, Record<string, Record<string, unknown>>>;")
	fmt.Fprintln(os.Stdout, "}")
	fmt.Fprintln(os.Stdout)

	fmt.Fprintln(os.Stdout, "export interface TableDiffMsg {")
	fmt.Fprintln(os.Stdout, "  type: 'table_diff';")
	fmt.Fprintln(os.Stdout, "  table: string;")
	fmt.Fprintln(os.Stdout, "  id: string;")
	fmt.Fprintln(os.Stdout, "  ver: number;")
	fmt.Fprintln(os.Stdout, "  patch: PatchOp[];")
	fmt.Fprintln(os.Stdout, "}")
	fmt.Fprintln(os.Stdout)

	fmt.Fprintln(os.Stdout, "export interface ViewDiffMsg {")
	fmt.Fprintln(os.Stdout, "  type: 'view_diff';")
	fmt.Fprintln(os.Stdout, "  view: string;")
	fmt.Fprintln(os.Stdout, "  params_hash: string;")
	fmt.Fprintln(os.Stdout, "  version: number;")
	fmt.Fprintln(os.Stdout, "  refs_patch: PatchOp[];")
	fmt.Fprintln(os.Stdout, "  tables?: Record<string, Record<string, Record<string, unknown>>>;")
	fmt.Fprintln(os.Stdout, "}")
	fmt.Fprintln(os.Stdout)

	// Views mapped type
	fmt.Fprintln(os.Stdout, "export type Views = {")
	for _, def := range all {
		iface := toPascal(def.Key)
		fmt.Fprintf(os.Stdout, "  %q: { params: %sParams; result: %sResult };\n", def.Key, iface, iface)
	}
	fmt.Fprintln(os.Stdout, "};")
}

func toPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func goTypeToTS(goType string) string {
	switch goType {
	case "uuid", "string":
		return "string"
	case "int":
		return "number"
	default:
		return "unknown"
	}
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
