// Auto-generated by arcana-gen. Do not edit.

export interface Views {
  catalog_categories_tree: {
    params: {
    };
    deps: {
      entities: ["name", "parent_id", "sort_order"];
    };
  };
  catalog_product_detail: {
    params: {
      product_id: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
      stock_levels: ["quantity", "reserved"];
    };
  };
  catalog_products_list: {
    params: {
      category_id?: string;
      limit?: number;
      offset?: number;
      search?: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
    };
  };
  crm_customer_detail: {
    params: {
      id: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
      orders: ["status", "total"];
    };
  };
  crm_customers_list: {
    params: {
      category?: string;
      limit?: number;
      offset?: number;
      search?: string;
      tag?: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
    };
  };
  crm_suppliers_list: {
    params: {
      limit?: number;
      offset?: number;
      search?: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
    };
  };
  dashboard_summary: {
    params: {
    };
    deps: {
      orders: ["status", "total", "created_at"];
      stock_levels: ["quantity", "min_quantity"];
      entities: ["status"];
    };
  };
  finance_account_balance: {
    params: {
      account_id: string;
    };
    deps: {
      accounts: ["code", "name"];
      transactions: ["is_posted"];
    };
  };
  finance_cash_operations: {
    params: {
      limit?: number;
      offset?: number;
    };
    deps: {
      cash_operations: ["type", "amount", "created_at"];
    };
  };
  finance_periods_list: {
    params: {
    };
    deps: {
      finance_periods: ["status", "closed_at"];
    };
  };
  finance_pnl: {
    params: {
      from: string;
      to: string;
    };
    deps: {
      accounts: ["code", "name", "type"];
      transactions: ["is_posted", "date"];
    };
  };
  finance_transactions_list: {
    params: {
      account_id?: string;
      limit?: number;
      offset?: number;
    };
    deps: {
      transactions: ["date", "description", "is_posted"];
    };
  };
  finance_trial_balance: {
    params: {
    };
    deps: {
      accounts: ["code", "name", "type"];
      transactions: ["is_posted"];
    };
  };
  hr_absences_list: {
    params: {
      employee_id?: string;
      limit?: number;
      offset?: number;
      status?: string;
    };
    deps: {
      absences: ["type", "status", "start_date", "end_date"];
      entities: ["name"];
    };
  };
  hr_employee_detail: {
    params: {
      employee_id: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
      shifts: ["start_time", "end_time", "status"];
    };
  };
  hr_employees_list: {
    params: {
      limit?: number;
      offset?: number;
      search?: string;
      status?: string;
    };
    deps: {
      entities: ["name", "status"];
      components: ["data"];
    };
  };
  hr_payroll_list: {
    params: {
      month: number;
      year: number;
    };
    deps: {
      payrolls: ["status", "net_salary", "gross_salary"];
      entities: ["name"];
    };
  };
  hr_shifts_schedule: {
    params: {
    };
    deps: {
      shifts: ["start_time", "end_time", "status"];
      entities: ["name"];
    };
  };
  hr_timesheets_list: {
    params: {
      employee_id?: string;
      limit?: number;
      offset?: number;
      status?: string;
    };
    deps: {
      timesheets: ["clock_in", "clock_out", "status"];
      entities: ["name"];
    };
  };
  logistics_route_detail: {
    params: {
      route_id: string;
    };
    deps: {
      routes: ["status", "planned_start", "actual_start", "actual_end"];
      route_stops: ["status", "actual_arrival"];
    };
  };
  logistics_routes_list: {
    params: {
      limit?: number;
      offset?: number;
      status?: string;
    };
    deps: {
      routes: ["status", "planned_start", "actual_start"];
      entities: ["name"];
    };
  };
  logistics_vehicles_map: {
    params: {
    };
    deps: {
      geo_tracks: ["latitude", "longitude"];
      entities: ["name"];
    };
  };
  notifications_list: {
    params: {
      limit?: number;
      offset?: number;
      unread_only?: string;
    };
    deps: {
      notifications: ["read", "iat"];
    };
  };
  notifications_unread: {
    params: {
    };
    deps: {
      notifications: ["read", "iat"];
    };
  };
  order_detail: {
    params: {
      order_id: string;
    };
    deps: {
      orders: ["status", "total", "updated_at"];
      order_items: ["quantity", "unit_price", "total"];
      entities: ["name"];
    };
  };
  order_refunds_list: {
    params: {
      limit?: number;
      offset?: number;
    };
    deps: {
      orders: ["status", "total", "refunded_at"];
    };
  };
  orders_dashboard: {
    params: {
    };
    deps: {
      orders: ["status", "total", "created_at"];
    };
  };
  orders_list: {
    params: {
      limit?: number;
      offset?: number;
      status?: string;
    };
    deps: {
      orders: ["status", "total", "updated_at"];
      entities: ["name"];
    };
  };
  organization_settings: {
    params: {
    };
    deps: {
      organization_settings: ["currency", "timezone", "features", "requisites"];
    };
  };
  warehouse_inventory_detail: {
    params: {
      product_id: string;
    };
    deps: {
      stock_levels: ["quantity", "reserved"];
      entities: ["name"];
    };
  };
  warehouse_low_stock: {
    params: {
      warehouse_id: string;
    };
    deps: {
      stock_levels: ["quantity", "reserved", "min_quantity"];
      entities: ["name"];
    };
  };
  warehouse_stock_detail: {
    params: {
      product_id: string;
      warehouse_id: string;
    };
    deps: {
      stock_levels: ["quantity", "reserved", "updated_at"];
      stock_movements: ["quantity", "type", "created_at"];
      entities: ["name"];
    };
  };
  warehouse_stock_list: {
    params: {
      limit?: number;
      offset?: number;
      search?: string;
      warehouse_id: string;
    };
    deps: {
      stock_levels: ["quantity", "reserved", "updated_at"];
      entities: ["name", "status"];
    };
  };
}
