// Auto-generated by gen_view_types.go — do not edit
// Generated: 2026-03-04T14:33:30Z

export type CatalogCategoriesTreeParams = Record<string, never>;

export interface CatalogCategoriesTreeResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface CatalogProductDetailParams {
  product_id?: string;
}

export interface CatalogProductDetailResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface CatalogProductsListParams {
  category_id?: string;
  search?: string;
}

export interface CatalogProductsListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export type DashboardSummaryParams = Record<string, never>;

export interface DashboardSummaryResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface FinanceAccountBalanceParams {
  account_id?: string;
}

export interface FinanceAccountBalanceResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface FinanceTransactionsListParams {
  account_id?: string;
}

export interface FinanceTransactionsListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export type FinanceTrialBalanceParams = Record<string, never>;

export interface FinanceTrialBalanceResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface HrEmployeeDetailParams {
  employee_id?: string;
}

export interface HrEmployeeDetailResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface HrEmployeesListParams {
  search?: string;
  status?: string;
}

export interface HrEmployeesListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export type HrShiftsScheduleParams = Record<string, never>;

export interface HrShiftsScheduleResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface HrTimesheetsListParams {
  employee_id?: string;
  status?: string;
}

export interface HrTimesheetsListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface LogisticsRouteDetailParams {
  route_id?: string;
}

export interface LogisticsRouteDetailResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface LogisticsRoutesListParams {
  status?: string;
}

export interface LogisticsRoutesListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export type LogisticsVehiclesMapParams = Record<string, never>;

export interface LogisticsVehiclesMapResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface OrderDetailParams {
  order_id?: string;
}

export interface OrderDetailResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export type OrdersDashboardParams = Record<string, never>;

export interface OrdersDashboardResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface OrdersListParams {
  status?: string;
}

export interface OrdersListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface WarehouseLowStockParams {
  warehouse_id?: string;
}

export interface WarehouseLowStockResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface WarehouseStockDetailParams {
  product_id?: string;
  warehouse_id?: string;
}

export interface WarehouseStockDetailResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface WarehouseStockListParams {
  warehouse_id?: string;
}

export interface WarehouseStockListResult {
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
  version: number;
}

export interface DataRef {
  table: string;
  id: string;
  fields: string[];
}

export interface PatchOp {
  op: 'add' | 'remove' | 'replace';
  path: string;
  value?: unknown;
}

export interface ViewSnapshotMsg {
  type: 'view_snapshot';
  view: string;
  params_hash: string;
  version: number;
  refs: DataRef[];
  tables: Record<string, Record<string, Record<string, unknown>>>;
}

export interface TableDiffMsg {
  type: 'table_diff';
  table: string;
  id: string;
  ver: number;
  patch: PatchOp[];
}

export interface ViewDiffMsg {
  type: 'view_diff';
  view: string;
  params_hash: string;
  version: number;
  refs_patch: PatchOp[];
  tables?: Record<string, Record<string, Record<string, unknown>>>;
}

export type Views = {
  "catalog_categories_tree": { params: CatalogCategoriesTreeParams; result: CatalogCategoriesTreeResult };
  "catalog_product_detail": { params: CatalogProductDetailParams; result: CatalogProductDetailResult };
  "catalog_products_list": { params: CatalogProductsListParams; result: CatalogProductsListResult };
  "dashboard_summary": { params: DashboardSummaryParams; result: DashboardSummaryResult };
  "finance_account_balance": { params: FinanceAccountBalanceParams; result: FinanceAccountBalanceResult };
  "finance_transactions_list": { params: FinanceTransactionsListParams; result: FinanceTransactionsListResult };
  "finance_trial_balance": { params: FinanceTrialBalanceParams; result: FinanceTrialBalanceResult };
  "hr_employee_detail": { params: HrEmployeeDetailParams; result: HrEmployeeDetailResult };
  "hr_employees_list": { params: HrEmployeesListParams; result: HrEmployeesListResult };
  "hr_shifts_schedule": { params: HrShiftsScheduleParams; result: HrShiftsScheduleResult };
  "hr_timesheets_list": { params: HrTimesheetsListParams; result: HrTimesheetsListResult };
  "logistics_route_detail": { params: LogisticsRouteDetailParams; result: LogisticsRouteDetailResult };
  "logistics_routes_list": { params: LogisticsRoutesListParams; result: LogisticsRoutesListResult };
  "logistics_vehicles_map": { params: LogisticsVehiclesMapParams; result: LogisticsVehiclesMapResult };
  "order_detail": { params: OrderDetailParams; result: OrderDetailResult };
  "orders_dashboard": { params: OrdersDashboardParams; result: OrdersDashboardResult };
  "orders_list": { params: OrdersListParams; result: OrdersListResult };
  "warehouse_low_stock": { params: WarehouseLowStockParams; result: WarehouseLowStockResult };
  "warehouse_stock_detail": { params: WarehouseStockDetailParams; result: WarehouseStockDetailResult };
  "warehouse_stock_list": { params: WarehouseStockListParams; result: WarehouseStockListResult };
};
